escape_data: "./SARS2_RBD_Ab_escape_maps/processed_data/escape_data.csv"
reference_genome: "./reference/NC_045512v2.fa"
reference_gtf: "./reference/ncbiGenes.gtf"
genbank: "./reference/hu1.gb"
lineage_params:
  floor: 100
  annotation: None
  missense: True
  gene: None
  minsamples: 15
  distinction: 1
  recursive: True
  cutoff: 0.99
  weight_params:
    escape_weighting: 100
    country_weighting: 10