escape_data: ./SARS2_RBD_Ab_escape_maps/processed_data/escape_data.csv
genbank: ./reference/hu1.gb
issue_params:
  local_only: true
  number: 20
  prefix: proposed_
  samples_named: 15
  sort_by: proposed_sublineage_score
lineage_params:
  annotation: B.1.1.529
  cutoff: 0.99
  distinction: 1
  earliest_date: 2022-12-21
  floor: 3
  gene: None
  minsamples: 10
  missense: true
  recursive: false
  weight_params:
    country_weighting: 10
    escape_weighting: 0
python: /home/jakob/anaconda3/envs/newusher/bin/python3.8
reference_genome: ./reference/NC_045512v2.fa
reference_gtf: ./reference/ncbiGenes.noORF1a.gtf
request_params:
  active_since: 2023-02-01
  auto_merge: false
  countries: 1
  designation_repo: ../auto-pango-designation
  growth_model:
    draws: 1000
    max_proportion_considered: 0.25
    min_country_weeks: 2
    target_accept: 0.9
    tune: 1500
    use_model: true
  local_only: false
  maximum: 20
  no_prefix: true
  representative_number: 1000
  samples_different: 5
  valid_samples: None
